name: Release

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

  generate_changelog:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate a changelog
        id: changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --verbose --bump
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Upload changelog for review
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: CHANGELOG.md

  manual_approval:
    runs-on: ubuntu-latest
    needs: generate_changelog
    steps:
      - name: Wait for manual approval
        uses: Midnighter/actions/manual-approval@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          approval-branch: main
          label: 'Approve changelog'
          comment: 'Please review the changelog and approve this workflow to continue with the release process.'

  commit_changelog:
    runs-on: ubuntu-latest
    needs: manual_approval
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download changelog
        uses: actions/download-artifact@v2
        with:
          name: changelog
          path: .

      - name: Commit changelog
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add CHANGELOG.md
          git commit -m "Update changelog"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main

  create_release:
    runs-on: ubuntu-latest
    needs: generate_changelog
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          bodyFile: CHANGELOG.md
