name: Release

on:
  push: '*'

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - name: Launch Release Please
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ github.token }}
